import { Movie } from './movie';

export const MOVIES: Movie[] = [
  {
    id: 0,
    movieTitle: 'Clash of the Wizards',
    yearReleased: 1997,
    monthReleased: 1,
    dateReleased: 3,
    yearReviewed: 2021,
    monthReviewed: 10,
    dateReviewed: 4,
    movDirector: 'Sack Zyder',
    movActor1: 'Mr Movie',
    movActor2: 'Danny Keys',
    movActor3: 'David Blue',
    reviewTitle: 'Solid Watch',
    reviewText: 'Good movie I liked it alot',
    movieRating: 4,
  },
  {
    id: 1,
    movieTitle: 'A Distant Stadium',
    yearReleased: 2007,
    monthReleased: 8,
    dateReleased: 19,
    yearReviewed: 2018,
    monthReviewed: 2,
    dateReviewed: 24,
    movDirector: 'Buzz Bee',
    movActor1: 'Stacey Lewis',
    movActor2: 'Stalin',
    movActor3: 'Kanye West',
    reviewTitle: 'Not for Everyone',
    reviewText: 'Many people enjoy this, but I do not.',
    movieRating: 1,
  },
  {
    id: 2,
    movieTitle: 'Wizard Boy and the Series of Events',
    yearReleased: 2001,
    monthReleased: 3,
    dateReleased: 2,
    yearReviewed: 2020,
    monthReviewed: 12,
    dateReviewed: 1,
    movDirector: 'Mr Knight',
    movActor1: 'Rudolf Reindeer',
    movActor2: 'Stan Lee',
    movActor3: 'Jane Doe',
    reviewTitle: 'It Is Okay',
    reviewText: 'This movie was entertaining.',
    movieRating: 3,
  },
  {
    id: 3,
    movieTitle: '21st Century Pandemic',
    yearReleased: 2019,
    monthReleased: 6,
    dateReleased: 15,
    yearReviewed: 2019,
    monthReviewed: 8,
    dateReviewed: 21,
    movDirector: 'Apollo Prophet',
    movActor1: 'Santa',
    movActor2: 'Mr Mime',
    movActor3: 'Chrisp Ratte',
    reviewTitle: 'Too Unrealistic',
    reviewText: 'An interesting take, but too unrealistic, will never happen',
    movieRating: 4,
  },
  {
    id: 4,
    movieTitle: 'Bee Movie 2: Electric Boogaloo',
    yearReleased: 1965,
    monthReleased: 9,
    dateReleased: 2,
    yearReviewed: 2022,
    monthReviewed: 7,
    dateReviewed: 20,
    movDirector: 'Jeff Kinney',
    movActor1: 'Danielle Blue',
    movActor2: 'Robert Downey Jr',
    movActor3: 'Ester Wester',
    reviewTitle: 'Bold, Enticing, Thouroughly Enjoyable',
    reviewText: 'Excellent watch and I highly recommnend',
    movieRating: 5,
  },
  {
    id: 5,
    movieTitle: 'Aliens on the Moon',
    yearReleased: 2010,
    monthReleased: 4,
    dateReleased: 10,
    yearReviewed: 2022,
    monthReviewed: 3,
    dateReviewed: 1,
    movDirector: 'Stephen Stevens',
    movActor1: 'Notta Hoomen',
    movActor2: 'Oprah Winfrey',
    movActor3: 'George Bush Sr',
    reviewTitle: 'Fun and Enjoyable',
    reviewText:
      'It has been done before but why the hell cant we do it again, right?',
    movieRating: 3,
  },
];
